# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20160410_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, default='', upload_to='static/img/profile_pics'),
            preserve_default=False,
        ),
    ]
