# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_auto_20160410_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expend',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
