# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('day_1_day', models.CharField(max_length=100)),
                ('day_1_day_price', models.PositiveIntegerField()),
                ('day_1_night', models.CharField(max_length=100)),
                ('day_1_night_price', models.PositiveIntegerField()),
                ('day_2_day', models.CharField(max_length=100)),
                ('day_2_day_price', models.PositiveIntegerField()),
                ('day_2_night', models.CharField(max_length=100)),
                ('day_2_night_price', models.PositiveIntegerField()),
                ('day_3_day', models.CharField(max_length=100)),
                ('day_3_day_price', models.PositiveIntegerField()),
                ('day_3_night', models.CharField(max_length=100)),
                ('day_3_night_price', models.PositiveIntegerField()),
            ],
        ),
    ]
