# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=27)),
                ('Name', models.CharField(max_length=50)),
                ('EntryNum', models.CharField(max_length=11)),
            ],
        ),
    ]
