# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='EntryNum',
            new_name='entry_num',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/img/profile_pics'),
        ),
    ]
