# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20160410_0517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
